In [2]:
import pandas as pd

In [4]:
df = pd.read_csv("/Users/matthewhugo/Documents/2026_neuefische_DataEng/de-week-1-Python/05_pandas_intro/data/abalone.csv")

In [9]:
df.head(1)

,sex,length,diameter,height,weight_whole,weight_shucked,viscera,shell,n_rings
0,M,0.455,0.365,0.095,0.514,0.2245,0.101,0.15,15

In [10]:
df.tail()

,sex,length,diameter,height,weight_whole,weight_shucked,viscera,shell,n_rings
4172,F,0.565,0.450,0.165,0.8870,0.3700,0.2390,0.2490,11
4173,M,0.590,0.440,0.135,0.9660,0.4390,0.2145,0.2605,10
4174,M,0.600,0.475,0.205,1.1760,0.5255,0.2875,0.3080,9
4175,F,0.625,0.485,0.150,1.0945,0.5310,0.2610,0.2960,10
4176,M,0.710,0.555,0.195,1.9485,0.9455,0.3765,0.4950,12

In [11]:
df.shape

(4177, 9)

In [12]:
df.columns

Index(['sex', 'length', 'diameter', 'height', 'weight_whole', 'weight_shucked',
       'viscera', 'shell', 'n_rings'],
      dtype='str')

In [13]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4177 entries, 0 to 4176
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   sex             4177 non-null   str
 1   length          4177 non-null   float64
 2   diameter        4177 non-null   float64
 3   height          4177 non-null   float64
 4   weight_whole    4177 non-null   float64
 5   weight_shucked  4177 non-null   float64
 6   viscera         4177 non-null   float64
 7   shell           4177 non-null   float64
 8   n_rings         4177 non-null   int64
dtypes: float64(7), int64(1), str(1)
memory usage: 293.8 KB

In [15]:
df.describe().round(2)

,length,diameter,height,weight_whole,weight_shucked,viscera,shell,n_rings
count,4177.00,4177.00,4177.00,4177.00,4177.00,4177.00,4177.00,4177.00
mean,0.52,0.41,0.14,0.83,0.36,0.18,0.24,9.93
std,0.12,0.10,0.04,0.49,0.22,0.11,0.14,3.22
min,0.08,0.06,0.00,0.00,0.00,0.00,0.00,1.00
25%,0.45,0.35,0.12,0.44,0.19,0.09,0.13,8.00
50%,0.55,0.42,0.14,0.80,0.34,0.17,0.23,9.00
75%,0.62,0.48,0.16,1.15,0.50,0.25,0.33,11.00
max,0.82,0.65,1.13,2.83,1.49,0.76,1.00,29.00

In [14]:
df['sex']

0       M
1       M
2       F
3       M
4       I
       ..
4172    F
4173    M
4174    M
4175    F
4176    M
Name: sex, Length: 4177, dtype: str

In [15]:
df.sex

0       M
1       M
2       F
3       M
4       I
       ..
4172    F
4173    M
4174    M
4175    F
4176    M
Name: sex, Length: 4177, dtype: str

In [16]:
df2 = df.copy()

In [18]:
cols = df2.columns.tolist()
cols

['sex',
 'length',
 'diameter',
 'height',
 'weight_whole',
 'weight_shucked',
 'viscera',
 'shell',
 'n_rings']

In [28]:
cols = [col.replace('__', '_') for col in cols]
cols

['sex',
 'length',
 'diameter',
 'height',
 'weight_whole',
 'weight_shucked',
 'viscera',
 'shell',
 'n_rings']

In [ ]:
df2.columns = cols
df2.head()

In [38]:
df.loc[:3,['sex', 'length', 'height']].round(2)

  sex  length  height
0   M    0.46    0.10
1   M    0.35    0.09
2   F    0.53    0.14
3   M    0.44    0.12

In [39]:
df.head(1)

,sex,length,diameter,height,weight_whole,weight_shucked,viscera,shell,n_rings
0,M,0.455,0.365,0.095,0.514,0.2245,0.101,0.15,15

In [42]:
df.iloc[:3, 1:4]

   length  diameter  height
0   0.455     0.365   0.095
1   0.350     0.265   0.090
2   0.530     0.420   0.135

In [ ]:
df[(df['length'] <= 0.4) & (df['sex'] == 'F')]

In [53]:
df[(df['length'] <= 0.4) & (df['sex'] == 'F')].iloc[1:5, 1:3]

     length  diameter
132   0.325     0.260
136   0.305     0.230
226   0.390     0.290
331   0.400     0.325

In [58]:
df.query("length <= 0.4 and sex == 'F'").iloc[:3, :4]

    sex  length  diameter  height
71    F   0.400      0.32    0.11
132   F   0.325      0.26    0.09
136   F   0.305      0.23    0.08

In [60]:
df['sex'].nunique()

3

In [75]:
group_by_obj = df.groupby('sex')

In [70]:
group_by_obj.mean().iloc[:3, :4].round(3)

     length  diameter  height  weight_whole
sex
F     0.579     0.455   0.158         1.047
I     0.428     0.326   0.108         0.431
M     0.561     0.439   0.151         0.991

In [66]:
group_by_obj.max().iloc[:3, :4]

     length  diameter  height  weight_whole
sex
F     0.815      0.65   1.130        2.6570
I     0.725      0.55   0.220        2.0495
M     0.780      0.63   0.515        2.8255

In [76]:
group_by_obj.count()['length']

sex
F    1307
I    1342
M    1528
Name: length, dtype: int64

In [ ]:
group_by_obj.count().iloc[:3, :4]

In [80]:
group_by_obj = df.groupby(['sex', 'n_rings']).count()['weight_whole']
group_by_obj

sex  n_rings
F    5            4
     6           16
     7           44
     8          122
     9          238
               ...
M    22           3
     23           3
     24           1
     26           1
     27           1
Name: weight_whole, Length: 68, dtype: int64

In [89]:
df.sort_values('length').head(5)

,sex,length,diameter,height,weight_whole,weight_shucked,viscera,shell,n_rings
236,I,0.075,0.055,0.010,0.0020,0.0010,0.0005,0.0015,1
238,I,0.110,0.090,0.030,0.0080,0.0025,0.0020,0.0030,3
2114,I,0.130,0.095,0.035,0.0105,0.0050,0.0065,0.0035,4
237,I,0.130,0.100,0.030,0.0130,0.0045,0.0030,0.0040,3
1986,I,0.135,0.130,0.040,0.0290,0.0125,0.0065,0.0080,4

In [98]:
df.rename(columns={'num_rings': 'nr_rings'}, inplace=True)
df.head()

,sex,length,diameter,height,weight_whole,weight_shucked,viscera,shell,nr_rings
0,M,0.455,0.365,0.095,0.5140,0.2245,0.1010,0.150,15
1,M,0.350,0.265,0.090,0.2255,0.0995,0.0485,0.070,7
2,F,0.530,0.420,0.135,0.6770,0.2565,0.1415,0.210,9
3,M,0.440,0.365,0.125,0.5160,0.2155,0.1140,0.155,10
4,I,0.330,0.255,0.080,0.2050,0.0895,0.0395,0.055,7

In [100]:
df.eval('age = nr_rings + 1.5', inplace = True)
df.columns
df.head()

,sex,length,diameter,height,weight_whole,weight_shucked,viscera,shell,nr_rings,age
0,M,0.455,0.365,0.095,0.5140,0.2245,0.1010,0.150,15,16.5
1,M,0.350,0.265,0.090,0.2255,0.0995,0.0485,0.070,7,8.5
2,F,0.530,0.420,0.135,0.6770,0.2565,0.1415,0.210,9,10.5
3,M,0.440,0.365,0.125,0.5160,0.2155,0.1140,0.155,10,11.5
4,I,0.330,0.255,0.080,0.2050,0.0895,0.0395,0.055,7,8.5

In [ ]:
df.drop('nr_rings', inplace=True, axis=1)

In [106]:
df.columns

Index(['sex', 'length', 'diameter', 'height', 'weight_whole', 'weight_shucked',
       'viscera', 'shell', 'age'],
      dtype='str')

In [107]:
df['length'] <= 0.3

0       False
1       False
2       False
3       False
4       False
        ...
4172    False
4173    False
4174    False
4175    False
4176    False
Name: length, Length: 4177, dtype: bool

In [110]:
type(df['length'] <= 0.3)

pandas.Series