### Part 1 - The Basics of DataFrames

1. Import pandas

In [1]:
import pandas as pd

2. Read the wine data into a DataFrame.

In [2]:
df = pd.read_csv('/Users/matthewhugo/Documents/2026_neuefische_DataEng/de-week-1-Python/05_pandas_intro/data/winequality-red.csv', sep=';')

df.columns

Index(['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol', 'quality'],
      dtype='str')

3. Use the `attributes` and `methods` available on DataFrames to answer the following questions.

In [ ]:
# How many rows and columns in DataFrame
df.shape

# Data type of each column
df.info()

# Continuous or Categorical 
df['quality'].unique() # labels a grade → categorical

# How many non-values 
df.info()
    # Can also use this:
df.isnull().sum()

# min, mean, max, median
df.describe()

In [39]:
df.columns = df.columns.str.replace(' ', '_')
df.head()

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5

### Part 2 - Practice with Grabbing Data

1. Grab the first 10 rows of the `chlorides` column.

In [ ]:
df[['chlorides']].head(10)

2. Grab the last 10 rows of the `chlorides` column.

In [ ]:
df[['chlorides']].tail(10)

3. Grab indices 264-282 of the `chlorides` **and** `density` columns.

In [ ]:
df.loc[264:282, ['chlorides', 'density']]

4. Grab all rows where the `chlorides` value is less than 0.10.

In [ ]:
df['chlorides'] < 0.10

5. Grab all rows where the `chlorides` value is greater than the column's mean.

In [ ]:

df[df['chlorides'] > df['chlorides'].mean()]

6. Grab all rows where the `pH` is greater than 3.0 and less than 3.5.

In [ ]:
df.query('pH > 3.0 and pH < 3.5')

7. Further filter the results from 6 to grab only those rows that have a `residual sugar` less than 2.0.

In [ ]:
df.query('pH > 3.0 and pH < 3.5 and residual_sugar <2.0')

### Part 3 - More Practice

1. Get the average amount of `chlorides` for each `quality` value.

In [69]:
df.groupby('quality')['chlorides'].mean()

quality
3    0.122500
4    0.090679
5    0.092736
6    0.084956
7    0.076588
8    0.068444
Name: chlorides, dtype: float64

2. For observations with a `pH` greater than 3.0 and less than 4.0, find the average `alcohol` value by `pH`.

In [ ]:

df.query('pH > 3.0 and pH < 4.0').groupby('pH')['alcohol'].mean()

3. For observations with an `alcohol` value between 9.25 and 9.5, find the highest amount of `residual sugar`.

In [53]:
df.query('alcohol > 9.25 and alcohol < 9.5')['residual_sugar'].max()

np.float64(10.7)

4. Create a new column, called `total_acidity`, that is the sum of `fixed acidity` and `volatile acidity`.

In [54]:
df.eval('total_acidity = fixed_acidity + volatile_acidity', inplace = True)
df.columns

Index(['fixed_acidity', 'volatile_acidity', 'citric_acid', 'residual_sugar',
       'chlorides', 'free_sulfur_dioxide', 'total_sulfur_dioxide', 'density',
       'pH', 'sulphates', 'alcohol', 'quality', 'total_acidity'],
      dtype='str')

In [55]:
df.head()

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality,total_acidity
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,8.10
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5,8.68
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5,8.56
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6,11.48
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,8.10

5. Find the average `total_acidity` for each of the `quality` values.

In [59]:
df.groupby('quality')[['total_acidity']].mean()

         total_acidity
quality
3             9.244500
4             8.473208
5             8.744295
6             8.844663
7             9.276281
8             8.990000

6. Find the top 5 `density` values.

In [61]:
df['density'].nlargest(5)

1434    1.00369
1435    1.00369
442     1.00320
554     1.00315
555     1.00315
Name: density, dtype: float64

7. Find the 10 lowest `sulphates` values.

In [70]:
df['sulphates'].nsmallest(10)

170     0.33
1287    0.37
1369    0.37
64      0.39
65      0.39
836     0.39
837     0.39
1347    0.39
1348    0.39
1234    0.40
Name: sulphates, dtype: float64